baseURL = "https://stultus.in/notes/"
languageCode = "en-us"
title = "stultus notes"
theme = "kavu"
themesdir = "./themes"
copyright = "Hrishikesh Bhaskaran ♥"
relativeURLs = false
canonifyURLs = false

[params]
  name = "Hrishikesh Bhaskaran"
  description = "The digital garden of Hrishikesh Bhaskaran (stultus) — a growing collection of notes, ideas, and explorations on software engineering, FOSS, language computing, and more."
  initials = "stultus notes"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://x.com/_stultus/"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/stultus"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/stultus/"
    icon = "fab fa-linkedin-in"

  [[params.social]]
    name = "Instagram"
    link = "https://instagram.com/stultusz"
    icon = "fab fa-instagram"

  [[params.social]]
    name = "Facebook"
    link = "https://www.facebook.com/stultus.hrishi"
    icon = "fab fa-facebook"


[menu]
  [[menu.main]]
    name = "blog"
    url = "https://stultus.in/post/"
    weight = 1
  [[menu.main]]
    name = "projects"
    url = "https://stultus.in/projects/"
    weight = 2
  [[menu.main]]
    name = "now"
    url = "https://stultus.in/now/"
    weight = 3
  [[menu.main]]
    name = "about"
    url = "https://stultus.in/about/"
    weight = 4
  [[menu.main]]
    name = "notes"
    url = "https://stultus.in/notes/"
    weight = 5


[taxonomies]
  tag = "tags"


[markup]
  [markup.highlight]
    noClasses = false
    style = 'monokai' # You can choose any built-in style or leave it blank

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

enableRobotsTXT = true
